# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - aliyun_prometheus Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class AliyunPrometheusV100(UModelCoreObject):
    """aliyun_prometheus class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # 阿里云 Prometheus 的核心配置部分，定义监控实例的连接和采集参数。
    spec: Optional['AliyunPrometheusV100Spec'] = None

    def get_kind(self) -> str:
        return 'aliyun_prometheus'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class AliyunPrometheusV100Spec:
    """阿里云 Prometheus 的核心配置部分，定义监控实例的连接和采集参数。"""
    # 阿里云 Prometheus 实例所属区域。
    region: Optional[str] = None
    # 阿里云 Prometheus 的实例ID。
    instance_id: Optional[str] = None
    # 阿里云 Prometheus 数据存储所在的 SLS 项目名称。
    sls_project: Optional[str] = None
    # 阿里云 Prometheus 数据存储所在的 SLS 时序库名称。
    sls_metricstore: Optional[str] = None
