# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - 基础类型定义
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union
import json
import yaml

@dataclass
class SemanticString:
    """支持多语言的语义字符串"""
    zh_cn: Optional[str] = None
    en_us: Optional[str] = None

    def __str__(self) -> str:
        """返回中文描述，如果没有则返回英文"""
        if self.zh_cn:
            return self.zh_cn
        return self.en_us or ''

    def get(self, lang: str) -> str:
        """根据语言代码获取对应文本"""
        if lang == 'zh_cn' or lang == 'zh':
            return self.zh_cn or ''
        elif lang == 'en_us' or lang == 'en':
            return self.en_us or ''
        return ''

    @classmethod
    def from_dict(cls, data: Union[str, Dict[str, str]]) -> 'SemanticString':
        """从字典或字符串创建SemanticString"""
        if isinstance(data, str):
            return cls(zh_cn=data, en_us=data)
        elif isinstance(data, dict):
            return cls(
                zh_cn=data.get('zh_cn'),
                en_us=data.get('en_us')
            )
        return cls()

@dataclass
class LinkEndpoint:
    """表示Link的端点信息"""
    domain: str
    kind: str
    name: str
    filter: Optional[str] = None

class UModelObject(ABC):
    """所有UModel对象的基础接口"""

    @abstractmethod
    def get_kind(self) -> str:
        """获取对象的类型标识"""
        pass

    def validate(self) -> Optional[Exception]:
        """验证对象是否符合schema定义"""
        # TODO: 实现验证逻辑
        return None

class UModelCoreObject(UModelObject):
    """所有core目录对象的接口"""

    @abstractmethod
    def get_schema(self) -> Optional[Any]:
        """获取对象的Schema信息"""
        pass

    @abstractmethod
    def get_metadata(self) -> Optional[Any]:
        """获取对象的Metadata信息"""
        pass

class UModelLinkObject(UModelCoreObject):
    """所有link类型对象的接口"""

    @abstractmethod
    def get_src(self) -> Optional[LinkEndpoint]:
        """获取源对象信息"""
        pass

    @abstractmethod
    def get_dest(self) -> Optional[LinkEndpoint]:
        """获取目标对象信息"""
        pass
