# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - data_link Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class DataLinkV100(UModelLinkObject):
    """data_link class"""
    kind: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    schema: Optional[Dict[str, Any]] = None
    # DataLink 的核心配置部分，定义 EntitySet、DataSet 之间的映射和关联规则。
    spec: Optional['DataLinkV100Spec'] = None

    def get_kind(self) -> str:
        return 'data_link'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

    def get_src(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'src'):
            src = spec.src
            if src:
                return LinkEndpoint(
                    domain=getattr(src, 'domain', ''),
                    kind=getattr(src, 'kind', ''),
                    name=getattr(src, 'name', ''),
                    filter=getattr(src, 'filter', None)
                )
        return None

    def get_dest(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'dest'):
            dest = spec.dest
            if dest:
                return LinkEndpoint(
                    domain=getattr(dest, 'domain', ''),
                    kind=getattr(dest, 'kind', ''),
                    name=getattr(dest, 'name', '')
                )
        return None

@dataclass
class DataLinkV100Spec:
    """DataLink 的核心配置部分，定义 EntitySet、DataSet 之间的映射和关联规则。"""
    # 源 DataSet/EntitySet 和目标 DataSet 字段之间的映射关系。
    fields_mapping: Optional[Dict[str, str]] = None
    # DataLink 的类型。值不能为空。值必须是以下之一：produce（产生）、related_to（有关联，即弱连接）。
    data_link_type: Optional[str] = None
    # 关联目标数据的过滤器，即目标 DataSet 中只有部分数据和源数据有关联。例如存在一个通用的MetricSet，包含各种调用类型的指标，而源实体可能是DBClient，则可通过 data_fiter = "type='db'" 过滤出所有 db 类...
    data_filter: Optional[str] = None
