# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - entity_source_link Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class EntitySourceLinkV100(UModelLinkObject):
    """entity_source_link class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # EntitySourceLink 的核心配置部分，连接 EntitySource 与 EntitySet。
    spec: Optional['EntitySourceLinkV100Spec'] = None

    def get_kind(self) -> str:
        return 'entity_source_link'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

    def get_src(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'src'):
            src = spec.src
            if src:
                return LinkEndpoint(
                    domain=getattr(src, 'domain', ''),
                    kind=getattr(src, 'kind', ''),
                    name=getattr(src, 'name', ''),
                    filter=getattr(src, 'filter', None)
                )
        return None

    def get_dest(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'dest'):
            dest = spec.dest
            if dest:
                return LinkEndpoint(
                    domain=getattr(dest, 'domain', ''),
                    kind=getattr(dest, 'kind', ''),
                    name=getattr(dest, 'name', '')
                )
        return None

@dataclass
class EntitySourceLinkV100SpecSrc:
    """源 Set 的标识。值不能为空。"""
    # 源 Set 的域。
    domain: Optional[str] = None
    # 源 Set 的类型。值不能为空。
    kind: Optional[str] = None
    # 源 Set 的名称。值不能为空。
    name: Optional[str] = None

@dataclass
class EntitySourceLinkV100SpecDest:
    """目标 Set 的标识。值不能为空。"""
    # 目标 Set 的域。
    domain: Optional[str] = None
    # 目标 Set 的类型。值不能为空。
    kind: Optional[str] = None
    # 目标 Set 的名称。值不能为空。
    name: Optional[str] = None

@dataclass
class EntitySourceLinkV100Spec:
    """EntitySourceLink 的核心配置部分，连接 EntitySource 与 EntitySet。"""
    # 源 Set 的标识。值不能为空。
    src: Optional['EntitySourceLinkV100SpecSrc'] = None
    # 目标 Set 的标识。值不能为空。
    dest: Optional['EntitySourceLinkV100SpecDest'] = None
