# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - entity_source Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class EntitySourceV100(UModelCoreObject):
    """entity_source class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # EntitySource 的核心配置部分，定义导入任务的调度方式以及源数据存储。
    spec: Optional['EntitySourceV100Spec'] = None

    def get_kind(self) -> str:
        return 'entity_source'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class EntitySourceV100Spec:
    """EntitySource 的核心配置部分，定义导入任务的调度方式以及源数据存储。"""
    # 导入任务的构造/调度配置，支持灵活扩展键值对。
    constructor: Optional[Dict[str, Any]] = None
    # 源数据存储配置列表，每个元素为一个 map，支持灵活扩展字段。
    storages: Optional[List[Dict[str, Any]]] = None
