# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - entity_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class EntitySetV100(UModelCoreObject):
    """entity_set class"""
    kind: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    schema: Optional[Dict[str, Any]] = None
    # EntitySet 的核心配置部分，定义实体数据的结构和生命周期管理规则。
    spec: Optional['EntitySetV100Spec'] = None

    def get_kind(self) -> str:
        return 'entity_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class EntitySetV100Spec:
    """EntitySet 的核心配置部分，定义实体数据的结构和生命周期管理规则。"""
    # Entity 的首次被观测时间所在字段。参考：https://alidocs.dingtalk.com/i/nodes/XPwkYGxZV347LdvpHaABmZXgJAgozOKL
    first_observed_time_field: Optional[str] = None
    # Entity 最近被观测时间所在字段。参考：https://alidocs.dingtalk.com/i/nodes/XPwkYGxZV347LdvpHaABmZXgJAgozOKL
    last_observed_time_field: Optional[str] = None
    # Entity 的主键字段。值格式为唯一标识实体的字段名称列表。
    primary_key_fields: Optional[List[str]] = None
    # Entity 的 ID 生成器。表示该 EntitySet 的ID如何通过PrimaryKeyFields 生成。该字段类型为 string，需要符合 SPL 的表达式语法，执行返回为 string。如果为空，则使用默认的生成方式： lower(to...
    id_generator: Optional[str] = None
    # 保持活跃的持续时间，在最后观测时间加上保活秒数后，Entity 将被视为消失。默认为3600秒（1小时）。参考：https://alidocs.dingtalk.com/i/nodes/XPwkYGxZV347LdvpHaABmZXgJAgozOKL
    keep_alive_seconds: Optional[float] = None
    # 是否为动态生成，默认为false。为true时表示该实体为动态实体，会绑定 Storage，每次实体的内容由Storage 处获取，而非存储在 EntityStore 中。
    dynamic: Optional[bool] = None
