# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - event_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class EventSetV100(UModelCoreObject):
    """event_set class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # EventSet 的核心配置部分，定义事件数据的结构和处理方式。
    spec: Optional['EventSetV100Spec'] = None

    def get_kind(self) -> str:
        return 'event_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class EventSetV100SpecEntityFields:
    """实体字段，用于标识实体的 ID、域和类型"""
    # 实体 ID 字段
    entity_id: Optional[str] = None
    # 实体所属的域字段
    domain: Optional[str] = None
    # 实体类型字段，用于标识实体的类型
    entity_type: Optional[str] = None

@dataclass
class EventSetV100Spec:
    """EventSet 的核心配置部分，定义事件数据的结构和处理方式。"""
    # 实体字段，用于标识实体的 ID、域和类型
    entity_fields: Optional['EventSetV100SpecEntityFields'] = None
