# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - explorer_link Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ExplorerLinkV100(UModelLinkObject):
    """explorer_link class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['ExplorerLinkV100Spec'] = None

    def get_kind(self) -> str:
        return 'explorer_link'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

    def get_src(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'src'):
            src = spec.src
            if src:
                return LinkEndpoint(
                    domain=getattr(src, 'domain', ''),
                    kind=getattr(src, 'kind', ''),
                    name=getattr(src, 'name', ''),
                    filter=getattr(src, 'filter', None)
                )
        return None

    def get_dest(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'dest'):
            dest = spec.dest
            if dest:
                return LinkEndpoint(
                    domain=getattr(dest, 'domain', ''),
                    kind=getattr(dest, 'kind', ''),
                    name=getattr(dest, 'name', '')
                )
        return None

@dataclass
class ExplorerLinkV100Spec:
    """ExplorerLinkV100Spec inline class"""
    # 源 Dataset 和目标 Explorer 之间的字段映射关系。
    token_mapping: Optional[Dict[str, Any]] = None
    # 源 Dataset 和目标 Explorer 之间的字段替换关系。
    token_replace: Optional[Dict[str, str]] = None
    # Explorer 的配置动态。
    config: Optional[Dict[str, Any]] = None
