# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - explorer Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ExplorerV100(UModelCoreObject):
    """explorer class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['ExplorerV100Spec'] = None

    def get_kind(self) -> str:
        return 'explorer'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ExplorerV100Spec:
    """ExplorerV100Spec inline class"""
    # Explorer 的类型。
    type: Optional[str] = None
    # Explorer 的默认查询。
    query: Optional[str] = None
    # Explorer 的配置动态。
    config: Optional[Dict[str, Any]] = None
