# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - external_storage Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ExternalStorageV100(UModelCoreObject):
    """external_storage class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['ExternalStorageV100Spec'] = None

    def get_kind(self) -> str:
        return 'external_storage'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ExternalStorageV100Spec:
    """ExternalStorageV100Spec inline class"""
    # 外部存储的类型。
    type: Optional[str] = None
    # 外部存储的名称。
    name: Optional[str] = None
    # 外部存储的详细信息，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于表示该外部存储的标签。
    tags: Optional[Dict[str, str]] = None
