# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - metric_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class MetricSetV100(UModelCoreObject):
    """metric_set class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # MetricSet 的核心配置部分，定义监控指标的数据结构和采集规则。
    spec: Optional['MetricSetV100Spec'] = None

    def get_kind(self) -> str:
        return 'metric_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class MetricSetV100SpecLabels:
    """指标集的标签列表，建议标签通过 dynamic 方式自动生成。注意：此处的标签是 MetricSet 的通用标签，一般建议 MetricSet 只定义通用标签，不在 Metric 下定义额外的标签。"""
    # 标签列表，值格式参考 field 定义。
    keys: Optional[List[Optional['FieldSpecV1']]] = None
    # 是否动态生成，一般建议设置为 true。
    dynamic: Optional[bool] = None
    # 标签的过滤器，在 dynamic 为 true 时，会根据此过滤器进行过滤。
    filter: Optional[str] = None

@dataclass
class MetricSetV100Spec:
    """MetricSet 的核心配置部分，定义监控指标的数据结构和采集规则。"""
    # 指标集的标签列表，建议标签通过 dynamic 方式自动生成。注意：此处的标签是 MetricSet 的通用标签，一般建议 MetricSet 只定义通用标签，不在 Metric 下定义额外的标签。
    labels: Optional['MetricSetV100SpecLabels'] = None
    # 指标集的标签键。当前已废弃，待删除，请使用 labels 字段代替。
    label_keys: Optional[List[Optional['FieldSpecV1']]] = None
    # 详细的指标列表。
    metrics: Optional[List[Optional['MetricV1']]] = None
    # 指标的查询语法，取值包括：prom、spl、cms 。
    query_type: Optional[str] = None
    # 是否需要二次处理，即该 MetricSet 中指标是否需要二次处理才能被使用。例如 Prometheus 中的 counter/summary/histogram 等指标需要二次处理才能被使用。
    needs_processing: Optional[bool] = None
