# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - profile_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ProfileSetV100(UModelCoreObject):
    """profile_set class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # ProfileSet 的核心配置部分，定义 Profile 数据的数据结构和处理方式。
    spec: Optional['ProfileSetV100Spec'] = None

    def get_kind(self) -> str:
        return 'profile_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ProfileSetV100Spec:
    """ProfileSet 的核心配置部分，定义 Profile 数据的数据结构和处理方式。"""
    # 使用的 Profile 协议。指定 Profile 数据的格式和标准。
    protocol: Optional[str] = None
