# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - runbook_link Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class RunbookLinkV100(UModelLinkObject):
    """runbook_link class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # RunbookLink 的核心配置部分，定义关联关系。
    spec: Optional['RunbookLinkV100Spec'] = None

    def get_kind(self) -> str:
        return 'runbook_link'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

    def get_src(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'src'):
            src = spec.src
            if src:
                return LinkEndpoint(
                    domain=getattr(src, 'domain', ''),
                    kind=getattr(src, 'kind', ''),
                    name=getattr(src, 'name', ''),
                    filter=getattr(src, 'filter', None)
                )
        return None

    def get_dest(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'dest'):
            dest = spec.dest
            if dest:
                return LinkEndpoint(
                    domain=getattr(dest, 'domain', ''),
                    kind=getattr(dest, 'kind', ''),
                    name=getattr(dest, 'name', '')
                )
        return None

@dataclass
class RunbookLinkV100Spec:
    """RunbookLink 的核心配置部分，定义关联关系。"""
    # 上下文变量的映射关系，用于在执行 Runbook 时提供动态上下文变量。
    token_replace: Optional[Dict[str, Any]] = None
    # 源数据集字段到目标 Runbook 字段的映射关系，用于将数据集中的字段值传递给 Runbook 的输入参数。
    fields_mapping: Optional[Dict[str, str]] = None
