# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - runbook_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class RunbookSetV100(UModelCoreObject):
    """runbook_set class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # RunbookSet 的核心配置部分，定义各类操作手册。
    spec: Optional['RunbookSetV100Spec'] = None

    def get_kind(self) -> str:
        return 'runbook_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class RunbookSetV100Spec:
    """RunbookSet 的核心配置部分，定义各类操作手册。"""
    # 观察配置列表
    observations: Optional[List[Optional['ObservationV1']]] = None
    # 操作能力配置列表
    actions: Optional[List[Optional['ActionConfigV1']]] = None
    # 工具箱配置列表，每个工具箱包含共享配置和一组工具
    toolkits: Optional[List[Optional['ToolkitV1']]] = None
    # 知识库配置列表
    knowledge: Optional[List[Optional['KnowledgeConfigV1']]] = None
    # 自动化配置列表
    automations: Optional[List[Optional['AutomationConfigV1']]] = None
    # 技能配置列表，遵循 Agent Skills 规范
    skills: Optional[List[Optional['SkillConfigV1']]] = None
