# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - sls_entitystore Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class SlsEntitystoreV100(UModelCoreObject):
    """sls_entitystore class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['SlsEntitystoreV100Spec'] = None

    def get_kind(self) -> str:
        return 'sls_entitystore'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class SlsEntitystoreV100Spec:
    """SlsEntitystoreV100Spec inline class"""
    # SLS EntityStore 的区域。
    region: Optional[str] = None
    # SLS EntityStore 的项目。
    project: Optional[str] = None
    # SLS EntityStore 的工作空间。
    workspace: Optional[str] = None
