# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - sls_metricstore Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class SlsMetricstoreV100(UModelCoreObject):
    """sls_metricstore class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['SlsMetricstoreV100Spec'] = None

    def get_kind(self) -> str:
        return 'sls_metricstore'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class SlsMetricstoreV100Spec:
    """SlsMetricstoreV100Spec inline class"""
    # SLS MetricStore 的区域。
    region: Optional[str] = None
    # SLS MetricStore 的项目。
    project: Optional[str] = None
    # SLS MetricStore 的名称。
    store: Optional[str] = None
