# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - sls_logstore Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class SlsLogstoreV100(UModelCoreObject):
    """sls_logstore class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    spec: Optional['SlsLogstoreV100Spec'] = None

    def get_kind(self) -> str:
        return 'sls_logstore'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class SlsLogstoreV100Spec:
    """SlsLogstoreV100Spec inline class"""
    # SLS LogStore 的区域。
    region: Optional[str] = None
    # SLS LogStore 的项目。
    project: Optional[str] = None
    # SLS LogStore 的名称。
    store: Optional[str] = None
    # 日志库的过滤条件，如果日志库中存储了多种类型的数据，可使用此字段过滤目标数据。
    search_filter: Optional[str] = None
    # 日志库的 SPL 过滤条件，相比 search_filter 字段，SPL 过滤条件更加灵活，支持更复杂的过滤条件，但性能相对较差。
    spl_filter: Optional[str] = None
    # 基于 SPL 生成的视图，一般用于动态生成实体列表、连接等场景。注意：此场景每次需要重新生成视图，性能较差。
    spl_view: Optional[str] = None
    # 基于 SPL Notebook 计算出的结果，相比 spl_view 字段，相对更加独立，可直接执行且能 Join 多种数据源。注意：此场景每次需要重新计算生成，性能较差。
    spl_notebook: Optional[str] = None
    # 日志库的 SQL 过滤条件，相比 search_filter 字段，SQL 过滤条件更加灵活，支持更复杂的过滤条件，但性能相对较差。
    sql_filter: Optional[str] = None
    # 基于 SQL 生成的视图，一般用于动态生成实体列表、连接等场景。注意：此场景每次需要重新生成视图，性能较差。
    sql_view: Optional[str] = None
