# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - storage_link Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class StorageLinkV100(UModelLinkObject):
    """storage_link class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # StorageLink 的核心配置部分，定义 EntitySet/DataSet 和 Storage 之间的映射和关联规则。
    spec: Optional['StorageLinkV100Spec'] = None

    def get_kind(self) -> str:
        return 'storage_link'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

    def get_src(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'src'):
            src = spec.src
            if src:
                return LinkEndpoint(
                    domain=getattr(src, 'domain', ''),
                    kind=getattr(src, 'kind', ''),
                    name=getattr(src, 'name', ''),
                    filter=getattr(src, 'filter', None)
                )
        return None

    def get_dest(self) -> Optional[LinkEndpoint]:
        spec = getattr(self, 'spec', None)
        if spec and hasattr(spec, 'dest'):
            dest = spec.dest
            if dest:
                return LinkEndpoint(
                    domain=getattr(dest, 'domain', ''),
                    kind=getattr(dest, 'kind', ''),
                    name=getattr(dest, 'name', '')
                )
        return None

@dataclass
class StorageLinkV100Spec:
    """StorageLink 的核心配置部分，定义 EntitySet/DataSet 和 Storage 之间的映射和关联规则。"""
    # 用于定义简单的字段映射关系，例如 DataSet 中 Field 的名称与 Storage 中字段名称的映射关系。
    fields_mapping: Optional[Dict[str, str]] = None
