# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - trace_set Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class TraceSetV100(UModelCoreObject):
    """trace_set class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # TraceSet 的核心配置部分，定义追踪数据的结构和处理方式。
    spec: Optional['TraceSetV100Spec'] = None

    def get_kind(self) -> str:
        return 'trace_set'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class TraceSetV100Spec:
    """TraceSet 的核心配置部分，定义追踪数据的结构和处理方式。"""
    # TraceSet 的属性列表，值格式为定义追踪属性的字段规格列表。当前未使用。
    attribute_fields: Optional[List[Optional['FieldSpecV1']]] = None
    # TraceSet 的 trace_id 字段名称。
    trace_id_field: Optional[str] = None
    # TraceSet 的 span_id 字段名称。
    span_id_field: Optional[str] = None
    # TraceSet 的 parent_span_id 字段名称。
    parent_span_id_field: Optional[str] = None
    # 使用的追踪协议。指定追踪数据的格式和标准。
    protocol: Optional[str] = None
