// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// AliyunPrometheusV100 represents aliyun_prometheus
type AliyunPrometheusV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec 阿里云 Prometheus 的核心配置部分，定义监控实例的连接和采集参数。
	Spec *AliyunPrometheusV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证AliyunPrometheusV100是否符合schema定义
func (s *AliyunPrometheusV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取AliyunPrometheusV100的类型标识
func (s *AliyunPrometheusV100) GetKind() string {
	return "aliyun_prometheus"
}

// GetSchema 获取AliyunPrometheusV100的Schema信息
func (s *AliyunPrometheusV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取AliyunPrometheusV100的Metadata信息
func (s *AliyunPrometheusV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// AliyunPrometheusV100Spec 阿里云 Prometheus 的核心配置部分，定义监控实例的连接和采集参数。
type AliyunPrometheusV100Spec struct {
	// Region 阿里云 Prometheus 实例所属区域。
	Region string `json:"region" yaml:"region"`
	// InstanceId 阿里云 Prometheus 的实例ID。
	InstanceId string `json:"instance_id" yaml:"instance_id"`
	// SlsProject 阿里云 Prometheus 数据存储所在的 SLS 项目名称。
	SlsProject string `json:"sls_project,omitempty" yaml:"sls_project,omitempty"`
	// SlsMetricstore 阿里云 Prometheus 数据存储所在的 SLS 时序库名称。
	SlsMetricstore string `json:"sls_metricstore,omitempty" yaml:"sls_metricstore,omitempty"`
}

// Validate 验证AliyunPrometheusV100Spec是否符合schema定义
func (s *AliyunPrometheusV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
