// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"gopkg.in/yaml.v3"
	"time"
)

// SemanticString 支持多语言的语义字符串
type SemanticString struct {
	ZhCN string `json:"zh_cn,omitempty" yaml:"zh_cn,omitempty"`
	EnUS string `json:"en_us,omitempty" yaml:"en_us,omitempty"`
}

// String 返回中文描述，如果没有则返回英文
func (s *SemanticString) String() string {
	if s.ZhCN != "" {
		return s.ZhCN
	}
	return s.EnUS
}

// UnmarshalJSON implements json.Unmarshaler
func (s *SemanticString) UnmarshalJSON(data []byte) error {
	// 尝试解析为字符串
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		s.ZhCN = str
		s.EnUS = str
		return nil
	}

	// 尝试解析为对象
	type Alias SemanticString
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*s = SemanticString(alias)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler
func (s *SemanticString) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind == yaml.ScalarNode {
		s.ZhCN = value.Value
		s.EnUS = value.Value
		return nil
	}

	type Alias SemanticString
	var alias Alias
	if err := value.Decode(&alias); err != nil {
		return err
	}
	*s = SemanticString(alias)
	return nil
}

// UModelObject 所有UModel对象的基础接口
type UModelObject interface {
	// GetKind 获取对象的类型标识
	GetKind() string
	// Validate 验证对象是否符合schema定义
	Validate() error
}

// UModelCoreObject 所有core目录对象的接口
type UModelCoreObject interface {
	UModelObject
	// GetSchema 获取对象的Schema信息
	GetSchema() *SchemaV1
	// GetMetadata 获取对象的Metadata信息
	GetMetadata() *MetadataV1
}

// UModelLinkObject 所有link类型对象的接口
type UModelLinkObject interface {
	UModelCoreObject
	// GetSrc 获取源对象信息
	GetSrc() *LinkEndpoint
	// GetDest 获取目标对象信息
	GetDest() *LinkEndpoint
}

// LinkEndpoint 表示Link的端点信息
type LinkEndpoint struct {
	Domain string `json:"domain" yaml:"domain"`
	Kind   string `json:"kind" yaml:"kind"`
	Name   string `json:"name" yaml:"name"`
	Filter string `json:"filter,omitempty" yaml:"filter,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = time.Now
}
