// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// DataLinkV100 represents data_link
type DataLinkV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	// Spec DataLink 的核心配置部分，定义 EntitySet、DataSet 之间的映射和关联规则。
	Spec *DataLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证DataLinkV100是否符合schema定义
func (s *DataLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取DataLinkV100的类型标识
func (s *DataLinkV100) GetKind() string {
	return "data_link"
}

// GetSchema 获取DataLinkV100的Schema信息
func (s *DataLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取DataLinkV100的Metadata信息
func (s *DataLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取DataLinkV100的源端点信息
func (s *DataLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
			Filter: s.Spec.Src.Filter,
		}
	}
	return nil
}

// GetDest 获取DataLinkV100的目标端点信息
func (s *DataLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// DataLinkV100Spec DataLink 的核心配置部分，定义 EntitySet、DataSet 之间的映射和关联规则。
type DataLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// FieldsMapping 源 DataSet/EntitySet 和目标 DataSet 字段之间的映射关系。
	FieldsMapping map[string]string `json:"fields_mapping,omitempty" yaml:"fields_mapping,omitempty"`
	// DataLinkType DataLink 的类型。值不能为空。值必须是以下之一：produce（产生）、related_to（有关联，即弱连接）。
	DataLinkType string `json:"data_link_type,omitempty" yaml:"data_link_type,omitempty"`
	// DataFilter 关联目标数据的过滤器，即目标 DataSet 中只有部分数据和源数据有关联。例如存在一个通用的MetricSet，包含各种调用类型的指标，而源实体可能是DBClient，则可通过 data_fiter = "type='db'" 过滤出所有 db 类...
	DataFilter string `json:"data_filter,omitempty" yaml:"data_filter,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
