// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// EntitySetLinkV100 represents entity_set_link
type EntitySetLinkV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec EntitySetLink 的核心配置部分，定义 EntitySet 之间的映射和关联规则。
	Spec *EntitySetLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证EntitySetLinkV100是否符合schema定义
func (s *EntitySetLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取EntitySetLinkV100的类型标识
func (s *EntitySetLinkV100) GetKind() string {
	return "entity_set_link"
}

// GetSchema 获取EntitySetLinkV100的Schema信息
func (s *EntitySetLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取EntitySetLinkV100的Metadata信息
func (s *EntitySetLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取EntitySetLinkV100的源端点信息
func (s *EntitySetLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
			Filter: s.Spec.Src.Filter,
		}
	}
	return nil
}

// GetDest 获取EntitySetLinkV100的目标端点信息
func (s *EntitySetLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// EntitySetLinkV100Spec EntitySetLink 的核心配置部分，定义 EntitySet 之间的映射和关联规则。
type EntitySetLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// FieldsMapping EntitySetLink 的目标 EntitySet 字段映射。
	FieldsMapping map[string]string `json:"fields_mapping,omitempty" yaml:"fields_mapping,omitempty"`
	// Constructor EntitySetLink 的自动化生成配置。若配置了此字段，则后台会自动创建并维护任务，自动生成 EntitySetLink。
	Constructor map[string]interface{} `json:"constructor,omitempty" yaml:"constructor,omitempty"`
	// EntityLinkType EntityLinkSet 的链接类型。值不能为空。建议的取值有： - calls (调用) - runs (运行) - instance_of (实例) - parent_of (父级) - contains (包含) - balances (平衡...
	EntityLinkType string `json:"entity_link_type" yaml:"entity_link_type"`
	// Dynamic 是否为动态生成，默认为false。为true时表示该 EntitySetLink 为动态 Link，会绑定 Storage，每次 Link 的内容由Storage 处获取，而非存储在 EntityStore 中。
	Dynamic bool `json:"dynamic,omitempty" yaml:"dynamic,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
