// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// EntitySourceV100 represents entity_source
type EntitySourceV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec EntitySource 的核心配置部分，定义导入任务的调度方式以及源数据存储。
	Spec *EntitySourceV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证EntitySourceV100是否符合schema定义
func (s *EntitySourceV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取EntitySourceV100的类型标识
func (s *EntitySourceV100) GetKind() string {
	return "entity_source"
}

// GetSchema 获取EntitySourceV100的Schema信息
func (s *EntitySourceV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取EntitySourceV100的Metadata信息
func (s *EntitySourceV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// EntitySourceV100Spec EntitySource 的核心配置部分，定义导入任务的调度方式以及源数据存储。
type EntitySourceV100Spec struct {
	// Constructor 导入任务的构造/调度配置，支持灵活扩展键值对。
	Constructor map[string]interface{} `json:"constructor" yaml:"constructor"`
	// Storages 源数据存储配置列表，每个元素为一个 map，支持灵活扩展字段。
	Storages []map[string]interface{} `json:"storages" yaml:"storages"`
}

// Validate 验证EntitySourceV100Spec是否符合schema定义
func (s *EntitySourceV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
