// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// EntitySourceLinkV100 represents entity_source_link
type EntitySourceLinkV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec EntitySourceLink 的核心配置部分，连接 EntitySource 与 EntitySet。
	Spec *EntitySourceLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证EntitySourceLinkV100是否符合schema定义
func (s *EntitySourceLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取EntitySourceLinkV100的类型标识
func (s *EntitySourceLinkV100) GetKind() string {
	return "entity_source_link"
}

// GetSchema 获取EntitySourceLinkV100的Schema信息
func (s *EntitySourceLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取EntitySourceLinkV100的Metadata信息
func (s *EntitySourceLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取EntitySourceLinkV100的源端点信息
func (s *EntitySourceLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
		}
	}
	return nil
}

// GetDest 获取EntitySourceLinkV100的目标端点信息
func (s *EntitySourceLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// EntitySourceLinkV100SpecSrc 源 Set 的标识。值不能为空。
type EntitySourceLinkV100SpecSrc struct {
	// Domain 源 Set 的域。
	Domain string `json:"domain" yaml:"domain"`
	// Kind 源 Set 的类型。值不能为空。
	Kind string `json:"kind" yaml:"kind"`
	// Name 源 Set 的名称。值不能为空。
	Name string `json:"name" yaml:"name"`
}

// Validate 验证EntitySourceLinkV100SpecSrc是否符合schema定义
func (s *EntitySourceLinkV100SpecSrc) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// EntitySourceLinkV100SpecDest 目标 Set 的标识。值不能为空。
type EntitySourceLinkV100SpecDest struct {
	// Domain 目标 Set 的域。
	Domain string `json:"domain" yaml:"domain"`
	// Kind 目标 Set 的类型。值不能为空。
	Kind string `json:"kind" yaml:"kind"`
	// Name 目标 Set 的名称。值不能为空。
	Name string `json:"name" yaml:"name"`
}

// Validate 验证EntitySourceLinkV100SpecDest是否符合schema定义
func (s *EntitySourceLinkV100SpecDest) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// EntitySourceLinkV100Spec EntitySourceLink 的核心配置部分，连接 EntitySource 与 EntitySet。
type EntitySourceLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// Src 源 Set 的标识。值不能为空。
	Src *EntitySourceLinkV100SpecSrc `json:"src" yaml:"src"`
	// Dest 目标 Set 的标识。值不能为空。
	Dest *EntitySourceLinkV100SpecDest `json:"dest" yaml:"dest"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
