// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// EventSetV100 represents event_set
type EventSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec EventSet 的核心配置部分，定义事件数据的结构和处理方式。
	Spec *EventSetV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证EventSetV100是否符合schema定义
func (s *EventSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取EventSetV100的类型标识
func (s *EventSetV100) GetKind() string {
	return "event_set"
}

// GetSchema 获取EventSetV100的Schema信息
func (s *EventSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取EventSetV100的Metadata信息
func (s *EventSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// EventSetV100SpecEntityFields 实体字段，用于标识实体的 ID、域和类型
type EventSetV100SpecEntityFields struct {
	// EntityId 实体 ID 字段
	EntityId string `json:"entity_id,omitempty" yaml:"entity_id,omitempty"`
	// Domain 实体所属的域字段
	Domain string `json:"domain,omitempty" yaml:"domain,omitempty"`
	// EntityType 实体类型字段，用于标识实体的类型
	EntityType string `json:"entity_type,omitempty" yaml:"entity_type,omitempty"`
}

// Validate 验证EventSetV100SpecEntityFields是否符合schema定义
func (s *EventSetV100SpecEntityFields) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// EventSetV100Spec EventSet 的核心配置部分，定义事件数据的结构和处理方式。
type EventSetV100Spec struct {
	TelemetryDataV1 `yaml:",inline"` // 嵌入 telemetry_data:v1
	// EntityFields 实体字段，用于标识实体的 ID、域和类型
	EntityFields *EventSetV100SpecEntityFields `json:"entity_fields,omitempty" yaml:"entity_fields,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
