// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ExplorerV100 represents explorer
type ExplorerV100 struct {
	Kind     string            `json:"kind" yaml:"kind"`
	Schema   *SchemaV1         `json:"schema" yaml:"schema"`
	Metadata *MetadataV1       `json:"metadata" yaml:"metadata"`
	Spec     *ExplorerV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ExplorerV100是否符合schema定义
func (s *ExplorerV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ExplorerV100的类型标识
func (s *ExplorerV100) GetKind() string {
	return "explorer"
}

// GetSchema 获取ExplorerV100的Schema信息
func (s *ExplorerV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ExplorerV100的Metadata信息
func (s *ExplorerV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ExplorerV100Spec inline struct
type ExplorerV100Spec struct {
	// Type Explorer 的类型。
	Type string `json:"type" yaml:"type"`
	// Query Explorer 的默认查询。
	Query string `json:"query,omitempty" yaml:"query,omitempty"`
	// Config Explorer 的配置动态。
	Config map[string]interface{} `json:"config,omitempty" yaml:"config,omitempty"`
}

// Validate 验证ExplorerV100Spec是否符合schema定义
func (s *ExplorerV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
