// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ExplorerLinkV100 represents explorer_link
type ExplorerLinkV100 struct {
	Kind     string                `json:"kind" yaml:"kind"`
	Schema   *SchemaV1             `json:"schema" yaml:"schema"`
	Metadata *MetadataV1           `json:"metadata" yaml:"metadata"`
	Spec     *ExplorerLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ExplorerLinkV100是否符合schema定义
func (s *ExplorerLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ExplorerLinkV100的类型标识
func (s *ExplorerLinkV100) GetKind() string {
	return "explorer_link"
}

// GetSchema 获取ExplorerLinkV100的Schema信息
func (s *ExplorerLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ExplorerLinkV100的Metadata信息
func (s *ExplorerLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取ExplorerLinkV100的源端点信息
func (s *ExplorerLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
			Filter: s.Spec.Src.Filter,
		}
	}
	return nil
}

// GetDest 获取ExplorerLinkV100的目标端点信息
func (s *ExplorerLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// ExplorerLinkV100Spec inline struct with extends
type ExplorerLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// TokenMapping 源 Dataset 和目标 Explorer 之间的字段映射关系。
	TokenMapping map[string]interface{} `json:"token_mapping,omitempty" yaml:"token_mapping,omitempty"`
	// TokenReplace 源 Dataset 和目标 Explorer 之间的字段替换关系。
	TokenReplace map[string]string `json:"token_replace,omitempty" yaml:"token_replace,omitempty"`
	// Config Explorer 的配置动态。
	Config map[string]interface{} `json:"config,omitempty" yaml:"config,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
