// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ExternalStorageV100 represents external_storage
type ExternalStorageV100 struct {
	Kind     string                   `json:"kind" yaml:"kind"`
	Schema   *SchemaV1                `json:"schema" yaml:"schema"`
	Metadata *MetadataV1              `json:"metadata" yaml:"metadata"`
	Spec     *ExternalStorageV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ExternalStorageV100是否符合schema定义
func (s *ExternalStorageV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ExternalStorageV100的类型标识
func (s *ExternalStorageV100) GetKind() string {
	return "external_storage"
}

// GetSchema 获取ExternalStorageV100的Schema信息
func (s *ExternalStorageV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ExternalStorageV100的Metadata信息
func (s *ExternalStorageV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ExternalStorageV100Spec inline struct
type ExternalStorageV100Spec struct {
	// Type 外部存储的类型。
	Type string `json:"type" yaml:"type"`
	// Name 外部存储的名称。
	Name string `json:"name" yaml:"name"`
	// Properties 外部存储的详细信息，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于表示该外部存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ExternalStorageV100Spec是否符合schema定义
func (s *ExternalStorageV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
