// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// LogSetV100 represents log_set
type LogSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec LogSet 的核心配置部分，定义日志数据的结构和处理方式。
	Spec *TelemetryDataV1 `json:"spec" yaml:"spec"`
}

// Validate 验证LogSetV100是否符合schema定义
func (s *LogSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取LogSetV100的类型标识
func (s *LogSetV100) GetKind() string {
	return "log_set"
}

// GetSchema 获取LogSetV100的Schema信息
func (s *LogSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取LogSetV100的Metadata信息
func (s *LogSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
