// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// MetricSetV100 represents metric_set
type MetricSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec MetricSet 的核心配置部分，定义监控指标的数据结构和采集规则。
	Spec *MetricSetV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证MetricSetV100是否符合schema定义
func (s *MetricSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取MetricSetV100的类型标识
func (s *MetricSetV100) GetKind() string {
	return "metric_set"
}

// GetSchema 获取MetricSetV100的Schema信息
func (s *MetricSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取MetricSetV100的Metadata信息
func (s *MetricSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// MetricSetV100SpecLabels 指标集的标签列表，建议标签通过 dynamic 方式自动生成。注意：此处的标签是 MetricSet 的通用标签，一般建议 MetricSet 只定义通用标签，不在 Metric 下定义额外的标签。
type MetricSetV100SpecLabels struct {
	// Keys 标签列表，值格式参考 field 定义。
	Keys []*FieldSpecV1 `json:"keys,omitempty" yaml:"keys,omitempty"`
	// Dynamic 是否动态生成，一般建议设置为 true。
	Dynamic bool `json:"dynamic,omitempty" yaml:"dynamic,omitempty"`
	// Filter 标签的过滤器，在 dynamic 为 true 时，会根据此过滤器进行过滤。
	Filter string `json:"filter,omitempty" yaml:"filter,omitempty"`
}

// Validate 验证MetricSetV100SpecLabels是否符合schema定义
func (s *MetricSetV100SpecLabels) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// MetricSetV100Spec MetricSet 的核心配置部分，定义监控指标的数据结构和采集规则。
type MetricSetV100Spec struct {
	// Labels 指标集的标签列表，建议标签通过 dynamic 方式自动生成。注意：此处的标签是 MetricSet 的通用标签，一般建议 MetricSet 只定义通用标签，不在 Metric 下定义额外的标签。
	Labels *MetricSetV100SpecLabels `json:"labels,omitempty" yaml:"labels,omitempty"`
	// LabelKeys 指标集的标签键。当前已废弃，待删除，请使用 labels 字段代替。
	LabelKeys []*FieldSpecV1 `json:"label_keys,omitempty" yaml:"label_keys,omitempty"`
	// Metrics 详细的指标列表。
	Metrics []*MetricV1 `json:"metrics,omitempty" yaml:"metrics,omitempty"`
	// QueryType 指标的查询语法，取值包括：prom、spl、cms 。
	QueryType string `json:"query_type,omitempty" yaml:"query_type,omitempty"`
	// NeedsProcessing 是否需要二次处理，即该 MetricSet 中指标是否需要二次处理才能被使用。例如 Prometheus 中的 counter/summary/histogram 等指标需要二次处理才能被使用。
	NeedsProcessing bool `json:"needs_processing,omitempty" yaml:"needs_processing,omitempty"`
}

// Validate 验证MetricSetV100Spec是否符合schema定义
func (s *MetricSetV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
