// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ProfileSetV100 represents profile_set
type ProfileSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec ProfileSet 的核心配置部分，定义 Profile 数据的数据结构和处理方式。
	Spec *ProfileSetV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ProfileSetV100是否符合schema定义
func (s *ProfileSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ProfileSetV100的类型标识
func (s *ProfileSetV100) GetKind() string {
	return "profile_set"
}

// GetSchema 获取ProfileSetV100的Schema信息
func (s *ProfileSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ProfileSetV100的Metadata信息
func (s *ProfileSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ProfileSetV100Spec ProfileSet 的核心配置部分，定义 Profile 数据的数据结构和处理方式。
type ProfileSetV100Spec struct {
	TelemetryDataV1 `yaml:",inline"` // 嵌入 telemetry_data:v1
	// Protocol 使用的 Profile 协议。指定 Profile 数据的格式和标准。
	Protocol string `json:"protocol,omitempty" yaml:"protocol,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
