// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// RunbookLinkV100 represents runbook_link
type RunbookLinkV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec RunbookLink 的核心配置部分，定义关联关系。
	Spec *RunbookLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证RunbookLinkV100是否符合schema定义
func (s *RunbookLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取RunbookLinkV100的类型标识
func (s *RunbookLinkV100) GetKind() string {
	return "runbook_link"
}

// GetSchema 获取RunbookLinkV100的Schema信息
func (s *RunbookLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取RunbookLinkV100的Metadata信息
func (s *RunbookLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取RunbookLinkV100的源端点信息
func (s *RunbookLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
			Filter: s.Spec.Src.Filter,
		}
	}
	return nil
}

// GetDest 获取RunbookLinkV100的目标端点信息
func (s *RunbookLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// RunbookLinkV100Spec RunbookLink 的核心配置部分，定义关联关系。
type RunbookLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// TokenReplace 上下文变量的映射关系，用于在执行 Runbook 时提供动态上下文变量。
	TokenReplace map[string]interface{} `json:"token_replace,omitempty" yaml:"token_replace,omitempty"`
	// FieldsMapping 源数据集字段到目标 Runbook 字段的映射关系，用于将数据集中的字段值传递给 Runbook 的输入参数。
	FieldsMapping map[string]string `json:"fields_mapping,omitempty" yaml:"fields_mapping,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
