// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// RunbookSetV100 represents runbook_set
type RunbookSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec RunbookSet 的核心配置部分，定义各类操作手册。
	Spec *RunbookSetV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证RunbookSetV100是否符合schema定义
func (s *RunbookSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取RunbookSetV100的类型标识
func (s *RunbookSetV100) GetKind() string {
	return "runbook_set"
}

// GetSchema 获取RunbookSetV100的Schema信息
func (s *RunbookSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取RunbookSetV100的Metadata信息
func (s *RunbookSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// RunbookSetV100Spec RunbookSet 的核心配置部分，定义各类操作手册。
type RunbookSetV100Spec struct {
	// Observations 观察配置列表
	Observations []*ObservationV1 `json:"observations,omitempty" yaml:"observations,omitempty"`
	// Actions 操作能力配置列表
	Actions []*ActionConfigV1 `json:"actions,omitempty" yaml:"actions,omitempty"`
	// Toolkits 工具箱配置列表，每个工具箱包含共享配置和一组工具
	Toolkits []*ToolkitV1 `json:"toolkits,omitempty" yaml:"toolkits,omitempty"`
	// Knowledge 知识库配置列表
	Knowledge []*KnowledgeConfigV1 `json:"knowledge,omitempty" yaml:"knowledge,omitempty"`
	// Automations 自动化配置列表
	Automations []*AutomationConfigV1 `json:"automations,omitempty" yaml:"automations,omitempty"`
	// Skills 技能配置列表，遵循 Agent Skills 规范
	Skills []*SkillConfigV1 `json:"skills,omitempty" yaml:"skills,omitempty"`
}

// Validate 验证RunbookSetV100Spec是否符合schema定义
func (s *RunbookSetV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
