// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// SlsMetricstoreV100 represents sls_metricstore
type SlsMetricstoreV100 struct {
	Kind     string                  `json:"kind" yaml:"kind"`
	Schema   *SchemaV1               `json:"schema" yaml:"schema"`
	Metadata *MetadataV1             `json:"metadata" yaml:"metadata"`
	Spec     *SlsMetricstoreV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证SlsMetricstoreV100是否符合schema定义
func (s *SlsMetricstoreV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SlsMetricstoreV100的类型标识
func (s *SlsMetricstoreV100) GetKind() string {
	return "sls_metricstore"
}

// GetSchema 获取SlsMetricstoreV100的Schema信息
func (s *SlsMetricstoreV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取SlsMetricstoreV100的Metadata信息
func (s *SlsMetricstoreV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// SlsMetricstoreV100Spec inline struct
type SlsMetricstoreV100Spec struct {
	// Region SLS MetricStore 的区域。
	Region string `json:"region" yaml:"region"`
	// Project SLS MetricStore 的项目。
	Project string `json:"project" yaml:"project"`
	// Store SLS MetricStore 的名称。
	Store string `json:"store" yaml:"store"`
}

// Validate 验证SlsMetricstoreV100Spec是否符合schema定义
func (s *SlsMetricstoreV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
