// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// SlsLogstoreV100 represents sls_logstore
type SlsLogstoreV100 struct {
	Kind     string               `json:"kind" yaml:"kind"`
	Schema   *SchemaV1            `json:"schema" yaml:"schema"`
	Metadata *MetadataV1          `json:"metadata" yaml:"metadata"`
	Spec     *SlsLogstoreV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证SlsLogstoreV100是否符合schema定义
func (s *SlsLogstoreV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SlsLogstoreV100的类型标识
func (s *SlsLogstoreV100) GetKind() string {
	return "sls_logstore"
}

// GetSchema 获取SlsLogstoreV100的Schema信息
func (s *SlsLogstoreV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取SlsLogstoreV100的Metadata信息
func (s *SlsLogstoreV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// SlsLogstoreV100Spec inline struct
type SlsLogstoreV100Spec struct {
	// Region SLS LogStore 的区域。
	Region string `json:"region" yaml:"region"`
	// Project SLS LogStore 的项目。
	Project string `json:"project" yaml:"project"`
	// Store SLS LogStore 的名称。
	Store string `json:"store" yaml:"store"`
	// SearchFilter 日志库的过滤条件，如果日志库中存储了多种类型的数据，可使用此字段过滤目标数据。
	SearchFilter string `json:"search_filter,omitempty" yaml:"search_filter,omitempty"`
	// SplFilter 日志库的 SPL 过滤条件，相比 search_filter 字段，SPL 过滤条件更加灵活，支持更复杂的过滤条件，但性能相对较差。
	SplFilter string `json:"spl_filter,omitempty" yaml:"spl_filter,omitempty"`
	// SplView 基于 SPL 生成的视图，一般用于动态生成实体列表、连接等场景。注意：此场景每次需要重新生成视图，性能较差。
	SplView string `json:"spl_view,omitempty" yaml:"spl_view,omitempty"`
	// SplNotebook 基于 SPL Notebook 计算出的结果，相比 spl_view 字段，相对更加独立，可直接执行且能 Join 多种数据源。注意：此场景每次需要重新计算生成，性能较差。
	SplNotebook string `json:"spl_notebook,omitempty" yaml:"spl_notebook,omitempty"`
	// SqlFilter 日志库的 SQL 过滤条件，相比 search_filter 字段，SQL 过滤条件更加灵活，支持更复杂的过滤条件，但性能相对较差。
	SqlFilter string `json:"sql_filter,omitempty" yaml:"sql_filter,omitempty"`
	// SqlView 基于 SQL 生成的视图，一般用于动态生成实体列表、连接等场景。注意：此场景每次需要重新生成视图，性能较差。
	SqlView string `json:"sql_view,omitempty" yaml:"sql_view,omitempty"`
}

// Validate 验证SlsLogstoreV100Spec是否符合schema定义
func (s *SlsLogstoreV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
