// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// SlsEntitystoreV100 represents sls_entitystore
type SlsEntitystoreV100 struct {
	Kind     string                  `json:"kind" yaml:"kind"`
	Schema   *SchemaV1               `json:"schema" yaml:"schema"`
	Metadata *MetadataV1             `json:"metadata" yaml:"metadata"`
	Spec     *SlsEntitystoreV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证SlsEntitystoreV100是否符合schema定义
func (s *SlsEntitystoreV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SlsEntitystoreV100的类型标识
func (s *SlsEntitystoreV100) GetKind() string {
	return "sls_entitystore"
}

// GetSchema 获取SlsEntitystoreV100的Schema信息
func (s *SlsEntitystoreV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取SlsEntitystoreV100的Metadata信息
func (s *SlsEntitystoreV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// SlsEntitystoreV100Spec inline struct
type SlsEntitystoreV100Spec struct {
	// Region SLS EntityStore 的区域。
	Region string `json:"region" yaml:"region"`
	// Project SLS EntityStore 的项目。
	Project string `json:"project" yaml:"project"`
	// Workspace SLS EntityStore 的工作空间。
	Workspace string `json:"workspace" yaml:"workspace"`
}

// Validate 验证SlsEntitystoreV100Spec是否符合schema定义
func (s *SlsEntitystoreV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
