// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// StorageLinkV100 represents storage_link
type StorageLinkV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec StorageLink 的核心配置部分，定义 EntitySet/DataSet 和 Storage 之间的映射和关联规则。
	Spec *StorageLinkV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证StorageLinkV100是否符合schema定义
func (s *StorageLinkV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取StorageLinkV100的类型标识
func (s *StorageLinkV100) GetKind() string {
	return "storage_link"
}

// GetSchema 获取StorageLinkV100的Schema信息
func (s *StorageLinkV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取StorageLinkV100的Metadata信息
func (s *StorageLinkV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// GetSrc 获取StorageLinkV100的源端点信息
func (s *StorageLinkV100) GetSrc() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Src字段
	if s.Spec.Src != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Src.Domain,
			Kind:   s.Spec.Src.Kind,
			Name:   s.Spec.Src.Name,
			Filter: s.Spec.Src.Filter,
		}
	}
	return nil
}

// GetDest 获取StorageLinkV100的目标端点信息
func (s *StorageLinkV100) GetDest() *LinkEndpoint {
	if s == nil || s.Spec == nil {
		return nil
	}
	// 检查Spec是否有Dest字段
	if s.Spec.Dest != nil {
		return &LinkEndpoint{
			Domain: s.Spec.Dest.Domain,
			Kind:   s.Spec.Dest.Kind,
			Name:   s.Spec.Dest.Name,
		}
	}
	return nil
}

// StorageLinkV100Spec StorageLink 的核心配置部分，定义 EntitySet/DataSet 和 Storage 之间的映射和关联规则。
type StorageLinkV100Spec struct {
	LinkV1 `yaml:",inline"` // 嵌入 link:v1
	// FieldsMapping 用于定义简单的字段映射关系，例如 DataSet 中 Field 的名称与 Storage 中字段名称的映射关系。
	FieldsMapping map[string]string `json:"fields_mapping,omitempty" yaml:"fields_mapping,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
