// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// TraceSetV100 represents trace_set
type TraceSetV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec TraceSet 的核心配置部分，定义追踪数据的结构和处理方式。
	Spec *TraceSetV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证TraceSetV100是否符合schema定义
func (s *TraceSetV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取TraceSetV100的类型标识
func (s *TraceSetV100) GetKind() string {
	return "trace_set"
}

// GetSchema 获取TraceSetV100的Schema信息
func (s *TraceSetV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取TraceSetV100的Metadata信息
func (s *TraceSetV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// TraceSetV100Spec TraceSet 的核心配置部分，定义追踪数据的结构和处理方式。
type TraceSetV100Spec struct {
	TelemetryDataV1 `yaml:",inline"` // 嵌入 telemetry_data:v1
	// AttributeFields TraceSet 的属性列表，值格式为定义追踪属性的字段规格列表。当前未使用。
	AttributeFields []*FieldSpecV1 `json:"attribute_fields,omitempty" yaml:"attribute_fields,omitempty"`
	// TraceIdField TraceSet 的 trace_id 字段名称。
	TraceIdField string `json:"trace_id_field" yaml:"trace_id_field"`
	// SpanIdField TraceSet 的 span_id 字段名称。
	SpanIdField string `json:"span_id_field" yaml:"span_id_field"`
	// ParentSpanIdField TraceSet 的 parent_span_id 字段名称。
	ParentSpanIdField string `json:"parent_span_id_field,omitempty" yaml:"parent_span_id_field,omitempty"`
	// Protocol 使用的追踪协议。指定追踪数据的格式和标准。
	Protocol string `json:"protocol,omitempty" yaml:"protocol,omitempty"`
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
