#!/usr/bin/env python3
"""
UModel Schema Go SDK Generator

这个脚本基于base.yaml中定义的元数据规范，解析expanded_schemas目录中的YAML文件，
生成相应的Go SDK代码，支持从JSON和YAML中解析数据结构。

功能：
1. 基于base.yaml的元数据定义解析schema
2. 生成Go struct定义
3. 生成JSON/YAML解析方法
4. 支持未识别字段的保存（类似protobuf）
"""

import os
import yaml
import json
from pathlib import Path
from typing import Dict, Any, List, Optional, Set, Tuple
from collections import defaultdict
import re


class GoCodeGenerator:
    def __init__(self, base_schema_path: str, expanded_schemas_dir: str, output_dir: str):
        self.base_schema_path = Path(base_schema_path)
        self.expanded_schemas_dir = Path(expanded_schemas_dir)
        self.output_dir = Path(output_dir)
        
        # 加载base.yaml
        self.base_schema = self._load_base_schema()
        self.metadata_properties = self.base_schema.get("metadata_properties", {})
        self.additional_types = self.base_schema.get("additional_types", {})
        
        # 存储所有生成的类型，避免重复
        self.generated_types: Set[str] = set()
        
        # 存储内联结构体定义
        self.inline_structs: List[Tuple[str, List[str]]] = []
        
        # Go类型映射
        self.type_mapping = {
            "string": "string",
            "number": "float64",
            "integer": "int64",
            "float": "float64",
            "boolean": "bool",
            "bool": "bool",
            "object": "map[string]interface{}",
            "array": "[]interface{}",
            "map": "map[string]interface{}",
            "any": "interface{}",
            "json": "json.RawMessage",
            "json_object": "map[string]interface{}",
            "json_array": "[]interface{}",
            "time": "time.Time",
            "semantic_string": "*SemanticString",
            "enum": "string",
        }
        
    def _load_base_schema(self) -> Dict[str, Any]:
        """加载base.yaml文件"""
        try:
            with open(self.base_schema_path, 'r', encoding='utf-8') as f:
                return yaml.safe_load(f)
        except Exception as e:
            print(f"❌ 无法加载base.yaml: {e}")
            return {}
    
    def generate_all(self):
        """生成所有schema的Go代码"""
        print("🚀 开始生成Go SDK代码...")
        
        # 创建输出目录
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # 首先生成通用类型定义
        self._generate_common_types()
        
        # 遍历所有展开的schema文件
        for yaml_file in self.expanded_schemas_dir.glob("*.expanded.yaml"):
            if yaml_file.name in ["expansion_report.md", "validation_report.md"]:
                continue
                
            try:
                print(f"📄 处理schema: {yaml_file.stem.replace('.expanded', '')}")
                self._process_schema_file(yaml_file)
            except Exception as e:
                print(f"❌ 处理文件失败 {yaml_file}: {e}")
                import traceback
                traceback.print_exc()
        
        # 生成主包文件
        self._generate_main_package_file()
        
        print("✅ Go SDK代码生成完成！")
    
    def _generate_common_types(self):
        """生成通用类型定义"""
        content = []
        content.append("// Code generated by schema_go_generator.py. DO NOT EDIT.")
        content.append("")
        content.append("package umodel")
        content.append("")
        content.append("import (")
        content.append('\t"encoding/json"')
        content.append('\t"time"')
        content.append('\t"gopkg.in/yaml.v3"')
        content.append(")")
        content.append("")
        
        # 添加init函数来使用导入的包
        content.append("func init() {")
        content.append("\t// 使用导入的包，避免编译错误")
        content.append("\t_ = time.Now()")
        content.append("}")
        content.append("")
        
        # 生成SemanticString类型
        content.append("// SemanticString 支持多语言的语义字符串")
        content.append("type SemanticString struct {")
        content.append("\tZhCN string `json:\"zh_cn,omitempty\" yaml:\"zh_cn,omitempty\"`")
        content.append("\tEnUS string `json:\"en_us,omitempty\" yaml:\"en_us,omitempty\"`")
        content.append("}")
        content.append("")
        
        # 生成SemanticString的解析方法
        content.append("// UnmarshalJSON implements json.Unmarshaler")
        content.append("func (s *SemanticString) UnmarshalJSON(data []byte) error {")
        content.append("\t// 尝试解析为字符串")
        content.append("\tvar str string")
        content.append("\tif err := json.Unmarshal(data, &str); err == nil {")
        content.append("\t\ts.ZhCN = str")
        content.append("\t\ts.EnUS = str")
        content.append("\t\treturn nil")
        content.append("\t}")
        content.append("")
        content.append("\t// 尝试解析为对象")
        content.append("\ttype Alias SemanticString")
        content.append("\tvar alias Alias")
        content.append("\tif err := json.Unmarshal(data, &alias); err != nil {")
        content.append("\t\treturn err")
        content.append("\t}")
        content.append("\t*s = SemanticString(alias)")
        content.append("\treturn nil")
        content.append("}")
        content.append("")
        
        # 生成UnmarshalYAML方法
        content.append("// UnmarshalYAML implements yaml.Unmarshaler")
        content.append("func (s *SemanticString) UnmarshalYAML(value *yaml.Node) error {")
        content.append("\t// 尝试解析为字符串")
        content.append("\tif value.Kind == yaml.ScalarNode {")
        content.append("\t\ts.ZhCN = value.Value")
        content.append("\t\ts.EnUS = value.Value")
        content.append("\t\treturn nil")
        content.append("\t}")
        content.append("")
        content.append("\t// 尝试解析为对象")
        content.append("\ttype Alias SemanticString")
        content.append("\tvar alias Alias")
        content.append("\tif err := value.Decode(&alias); err != nil {")
        content.append("\t\treturn err")
        content.append("\t}")
        content.append("\t*s = SemanticString(alias)")
        content.append("\treturn nil")
        content.append("}")
        content.append("")
        
        # 写入文件
        output_file = self.output_dir / "common_types.go"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(content))
        
        print(f"✅ 生成通用类型定义: {output_file.name}")
    
    def _process_schema_file(self, yaml_file: Path):
        """处理单个schema文件"""
        with open(yaml_file, 'r', encoding='utf-8') as f:
            schema = yaml.safe_load(f)
        
        if not schema or 'name' not in schema:
            return
        
        schema_name = schema['name']
        
        # 为每个schema创建一个单独的Go文件
        go_content = []
        go_content.append("// Code generated by schema_go_generator.py. DO NOT EDIT.")
        go_content.append("")
        go_content.append("package umodel")
        go_content.append("")
        go_content.append("import (")
        go_content.append('\t"encoding/json"')
        go_content.append('\t"time"')
        go_content.append('\t"gopkg.in/yaml.v3"')
        go_content.append(")")
        go_content.append("")
        
        # 添加init函数来使用导入的包
        go_content.append("func init() {")
        go_content.append("\t// 使用导入的包，避免编译错误")
        go_content.append("\t_ = time.Now()")
        go_content.append("}")
        go_content.append("")
        
        # 清空内联结构体列表
        self.inline_structs = []
        
        # 生成每个版本的struct
        if 'versions' in schema:
            for version in schema['versions']:
                version_name = version.get('name', 'v1')
                spec = version.get('spec', {})
                
                # 生成struct名称
                struct_name = self._to_go_struct_name(schema_name, version_name)
                
                # 生成struct定义
                self._generate_struct(go_content, struct_name, spec, schema_name)
                
                # 生成JSON/YAML解析方法
                self._generate_unmarshal_methods(go_content, struct_name, spec)
        
        # 生成所有内联结构体
        for inline_struct_name, inline_struct_content in self.inline_structs:
            go_content.extend(inline_struct_content)
        
        # 写入文件
        output_file = self.output_dir / f"{schema_name}.go"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(go_content))
        
        print(f"✅ 生成Go代码: {output_file.name}")
    
    def _generate_struct(self, content: List[str], struct_name: str, spec: Dict[str, Any], schema_name: str):
        """生成struct定义"""
        # 生成struct注释
        if 'description' in spec:
            desc = self._get_description(spec['description'])
            content.append(f"// {struct_name} {desc}")
        else:
            content.append(f"// {struct_name} represents {schema_name}")
        
        content.append(f"type {struct_name} struct {{")
        
        # 处理properties
        if 'properties' in spec and isinstance(spec['properties'], dict):
            for prop_name, prop_spec in spec['properties'].items():
                self._generate_struct_field(content, prop_name, prop_spec, struct_name)
        
        content.append("}")
        content.append("")
    
    def _generate_struct_field(self, content: List[str], field_name: str, field_spec: Dict[str, Any], parent_struct_name: str):
        """生成struct字段"""
        # 检查field_spec是否有效
        if field_spec is None:
            return
            
        # 获取字段描述
        desc = ""
        if isinstance(field_spec, dict) and 'description' in field_spec:
            desc = self._get_description(field_spec['description'])
        
        # 获取Go类型
        go_type = self._get_go_type(field_spec, field_name, parent_struct_name)
        
        # 获取字段标签
        json_tag = self._to_json_field_name(field_name)
        yaml_tag = field_name
        
        # 检查是否必填
        is_required = False
        if isinstance(field_spec, dict) and 'constraint' in field_spec:
            constraint = field_spec['constraint']
            if isinstance(constraint, dict):
                is_required = constraint.get('required', False)
        
        if not is_required:
            json_tag += ",omitempty"
            yaml_tag += ",omitempty"
        
        # 生成字段
        go_field_name = self._to_go_field_name(field_name)
        
        if desc:
            content.append(f"\t// {go_field_name} {desc}")
        content.append(f'\t{go_field_name} {go_type} `json:"{json_tag}" yaml:"{yaml_tag}"`')
    
    def _get_go_type(self, spec: Dict[str, Any], field_name: str = "", parent_struct_name: str = "") -> str:
        """获取字段的Go类型"""
        # 检查spec是否为有效的dict
        if not isinstance(spec, dict):
            return "interface{}"
            
        # 处理constraint中定义的类型
        if 'constraint' in spec:
            constraint = spec['constraint']
            
            # 检查constraint是否为None
            if constraint is not None:
                # 处理array约束
                if 'array' in constraint and 'item' in constraint['array']:
                    item_spec = constraint['array']['item']
                    item_type = self._get_go_type(item_spec, f"{field_name}_item", parent_struct_name)
                    return f"[]{item_type}"
                
                # 处理map约束
                if 'map' in constraint:
                    value_spec = constraint['map'].get('value', {'type': 'string'})
                    value_type = self._get_go_type(value_spec, f"{field_name}_value", parent_struct_name)
                    return f"map[string]{value_type}"
                
                # 处理oneOf约束
                if 'oneOf' in constraint:
                    # 简化处理：使用interface{}
                    return "interface{}"
        
        # 处理基本类型
        if 'type' in spec:
            base_type = spec['type']
            
            # 处理object类型的properties
            if base_type == 'object' and 'properties' in spec:
                props = spec['properties']
                
                # 检查是否是semantic_string的展开形式
                if isinstance(props, dict) and set(props.keys()) <= {"zh_cn", "en_us"}:
                    # 检查属性类型是否都是string
                    all_string = all(
                        isinstance(prop, dict) and prop.get('type') == 'string' 
                        for prop in props.values() 
                        if prop is not None
                    )
                    if all_string:
                        return "*SemanticString"
                
                # 生成内联struct
                if field_name and parent_struct_name:
                    inline_struct_name = f"{parent_struct_name}{self._to_go_field_name(field_name)}"
                    self._generate_inline_struct(inline_struct_name, spec)
                    return f"*{inline_struct_name}"
                else:
                    return "map[string]interface{}"
            
            # 处理map类型
            elif base_type == 'map':
                # 从constraint中获取value的类型
                if 'constraint' in spec and spec['constraint'] is not None and 'map' in spec['constraint']:
                    value_spec = spec['constraint']['map'].get('value', {'type': 'string'})
                    value_type = self._get_go_type(value_spec, f"{field_name}_value", parent_struct_name)
                    return f"map[string]{value_type}"
                return "map[string]interface{}"
            
            return self.type_mapping.get(base_type, "interface{}")
        
        return "interface{}"
    
    def _generate_inline_struct(self, struct_name: str, spec: Dict[str, Any]):
        """生成内联结构体定义"""
        content = []
        
        # 生成struct注释
        if 'description' in spec:
            desc = self._get_description(spec['description'])
            content.append(f"// {struct_name} {desc}")
        else:
            content.append(f"// {struct_name} inline struct")
        
        content.append(f"type {struct_name} struct {{")
        
        # 处理properties
        if 'properties' in spec and isinstance(spec['properties'], dict):
            for prop_name, prop_spec in spec['properties'].items():
                # 跳过None的prop_spec
                if prop_spec is None:
                    continue
                    
                # 生成字段
                desc = ""
                if isinstance(prop_spec, dict) and 'description' in prop_spec:
                    desc = self._get_description(prop_spec['description'])
                
                go_type = self._get_go_type(prop_spec, prop_name, struct_name)
                json_tag = self._to_json_field_name(prop_name)
                yaml_tag = prop_name
                
                is_required = False
                if isinstance(prop_spec, dict) and 'constraint' in prop_spec:
                    constraint = prop_spec['constraint']
                    if isinstance(constraint, dict):
                        is_required = constraint.get('required', False)
                
                if not is_required:
                    json_tag += ",omitempty"
                    yaml_tag += ",omitempty"
                
                go_field_name = self._to_go_field_name(prop_name)
                
                if desc:
                    content.append(f"\t// {go_field_name} {desc}")
                content.append(f'\t{go_field_name} {go_type} `json:"{json_tag}" yaml:"{yaml_tag}"`')
        
        content.append("}")
        content.append("")
        
        # 添加到内联结构体列表
        self.inline_structs.append((struct_name, content))
    
    def _generate_unmarshal_methods(self, content: List[str], struct_name: str, spec: Dict[str, Any]):
        """生成JSON和YAML的解析方法"""
        # 生成UnmarshalJSON方法
        content.append(f"// UnmarshalJSON implements json.Unmarshaler")
        content.append(f"func (s *{struct_name}) UnmarshalJSON(data []byte) error {{")
        content.append("\t// 使用默认的JSON解析")
        content.append(f"\ttype Alias {struct_name}")
        content.append("\tvar alias Alias")
        content.append("\tif err := json.Unmarshal(data, &alias); err != nil {")
        content.append("\t\treturn err")
        content.append("\t}")
        content.append(f"\t*s = {struct_name}(alias)")
        content.append("\treturn nil")
        content.append("}")
        content.append("")
        
        # 生成UnmarshalYAML方法
        content.append(f"// UnmarshalYAML implements yaml.Unmarshaler")
        content.append(f"func (s *{struct_name}) UnmarshalYAML(value *yaml.Node) error {{")
        content.append("\t// 使用默认的YAML解析")
        content.append(f"\ttype Alias {struct_name}")
        content.append("\tvar alias Alias")
        content.append("\tif err := value.Decode(&alias); err != nil {")
        content.append("\t\treturn err")
        content.append("\t}")
        content.append(f"\t*s = {struct_name}(alias)")
        content.append("\treturn nil")
        content.append("}")
        content.append("")
    
    def _generate_main_package_file(self):
        """生成主包文件和辅助函数"""
        content = []
        content.append("// Code generated by schema_go_generator.py. DO NOT EDIT.")
        content.append("")
        content.append("// Package umodel provides Go SDK for UModel Schema")
        content.append("package umodel")
        content.append("")
        content.append("import (")
        content.append('\t"encoding/json"')
        content.append('\t"io"')
        content.append('\t"gopkg.in/yaml.v3"')
        content.append(")")
        content.append("")
        content.append("// Version SDK版本")
        content.append('const Version = "1.0.0"')
        content.append("")
        
        # 添加解析辅助函数
        content.append("// ParseJSON 从JSON数据解析UModel对象")
        content.append("func ParseJSON(data []byte, v interface{}) error {")
        content.append("\treturn json.Unmarshal(data, v)")
        content.append("}")
        content.append("")
        
        content.append("// ParseYAML 从YAML数据解析UModel对象")
        content.append("func ParseYAML(data []byte, v interface{}) error {")
        content.append("\treturn yaml.Unmarshal(data, v)")
        content.append("}")
        content.append("")
        
        content.append("// ParseJSONReader 从Reader解析JSON格式的UModel对象")
        content.append("func ParseJSONReader(r io.Reader, v interface{}) error {")
        content.append("\tdecoder := json.NewDecoder(r)")
        content.append("\treturn decoder.Decode(v)")
        content.append("}")
        content.append("")
        
        content.append("// ParseYAMLReader 从Reader解析YAML格式的UModel对象")
        content.append("func ParseYAMLReader(r io.Reader, v interface{}) error {")
        content.append("\tdecoder := yaml.NewDecoder(r)")
        content.append("\treturn decoder.Decode(v)")
        content.append("}")
        content.append("")
        
        output_file = self.output_dir / "umodel.go"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(content))
        
        print(f"✅ 生成主包文件: {output_file.name}")
    
    def _to_go_struct_name(self, schema_name: str, version: str) -> str:
        """将schema名称转换为Go struct名称"""
        # 将下划线分隔的名称转换为驼峰命名
        parts = schema_name.split('_')
        struct_name = ''.join(word.capitalize() for word in parts)
        
        # 添加版本后缀
        version_suffix = version.replace('.', '').upper()
        return f"{struct_name}{version_suffix}"
    
    def _to_go_field_name(self, field_name: str) -> str:
        """将字段名转换为Go字段名（首字母大写的驼峰）"""
        parts = field_name.split('_')
        return ''.join(word.capitalize() for word in parts)
    
    def _to_json_field_name(self, field_name: str) -> str:
        """将字段名转换为JSON字段名"""
        return field_name
    
    def _get_description(self, desc: Any) -> str:
        """获取描述文本"""
        text = ""
        if isinstance(desc, str):
            text = desc
        elif isinstance(desc, dict):
            # 优先返回中文描述
            if 'zh_cn' in desc:
                text = desc['zh_cn']
            elif 'en_us' in desc:
                text = desc['en_us']
        
        if not text:
            return ""
        
        # 处理换行符，将多行文本合并为单行
        text = text.replace('\n', ' ').replace('\r', ' ')
        
        # 替换中文标点符号为英文标点
        replacements = {
            '，': ',',
            '。': '.',
            '：': ':',
            '；': ';',
            '！': '!',
            '？': '?',
            '"': '"',
            '"': '"',
            ''': "'",
            ''': "'",
            '（': '(',
            '）': ')',
            '【': '[',
            '】': ']',
            '、': ',',
            '°': ' degrees',
            '…': '...',
            '—': '-',
            '～': '~',
            '・': '·',
            '／': '/',
            '＼': '\\',
            '｜': '|',
            '＋': '+',
            '－': '-',
            '＊': '*',
            '＝': '=',
            '＜': '<',
            '＞': '>',
        }
        
        for old, new in replacements.items():
            text = text.replace(old, new)
        
        # 移除多余的空格
        text = ' '.join(text.split())
        
        # 限制长度为128字节
        # 注意：中文字符可能占用多个字节，所以我们需要按字节截断
        encoded = text.encode('utf-8')
        if len(encoded) > 128:
            # 找到合适的截断点，避免在多字节字符中间截断
            truncate_at = 125  # 留出空间给 "..."
            while truncate_at > 0:
                try:
                    truncated = encoded[:truncate_at].decode('utf-8')
                    return truncated + "..."
                except UnicodeDecodeError:
                    truncate_at -= 1
            return "..."
        
        return text


def main():
    """主函数"""
    print("🚀 UModel Schema Go SDK Generator 启动")
    print("=" * 50)
    
    # 配置路径
    base_schema_path = "schemas/base.yaml"
    expanded_schemas_dir = "expanded_schemas"
    output_dir = "generated/go/umodel"
    
    # 检查必要的目录和文件
    if not os.path.exists(expanded_schemas_dir):
        print(f"❌ expanded_schemas目录不存在: {expanded_schemas_dir}")
        print("请先运行 schema_expander.py 生成展开的schema文件")
        return
    
    if not os.path.exists(base_schema_path):
        print(f"❌ base.yaml文件不存在: {base_schema_path}")
        return
    
    # 创建生成器
    generator = GoCodeGenerator(base_schema_path, expanded_schemas_dir, output_dir)
    
    try:
        # 生成所有代码
        generator.generate_all()
        
        print(f"\n✅ Go SDK代码已生成到: {output_dir}")
        print("\n📝 使用说明:")
        print("1. 将生成的代码复制到您的Go项目中")
        print("2. 安装依赖: go get gopkg.in/yaml.v3")
        print("3. 导入包: import \"your-module/umodel\"")
        
    except Exception as e:
        print(f"\n❌ 生成过程中发生错误: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main() 